apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: popquiz-frontend-hpa
  namespace: popquiz
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: popquiz-frontend-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: popquiz-backend-hpa
  namespace: popquiz
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: popquiz-backend-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
