apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: popquiz-frontend-vpa
  namespace: popquiz
spec:
  targetRef:
    apiVersion: 'apps/v1'
    kind: Deployment
    name: popquiz-frontend
  updatePolicy:
    updateMode: 'Auto'

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: popquiz-backend-vpa
  namespace: popquiz
spec:
  targetRef:
    apiVersion: 'apps/v1'
    kind: Deployment
    name: popquiz-backend
  updatePolicy:
    updateMode: 'Auto'

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: popquiz-langchain-vpa
  namespace: popquiz
spec:
  targetRef:
    apiVersion: 'apps/v1'
    kind: Deployment
    name: popquiz-langchain
  updatePolicy:
    updateMode: 'Auto'

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: popquiz-redis-vpa
  namespace: popquiz
spec:
  targetRef:
    apiVersion: 'apps/v1'
    kind: StatefulSet
    name: popquiz-redis
  updatePolicy:
    updateMode: 'Auto'

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: popquiz-qdrant-vpa
  namespace: popquiz
spec:
  targetRef:
    apiVersion: 'apps/v1'
    kind: StatefulSet
    name: popquiz-qdrant
  updatePolicy:
    updateMode: 'Auto'
