namespace: popquiz

backend:
  name: popquiz-backend
  image: abhaytopno/popquiz-backend:v5
  port: 5000
  resources:
    requests:
      cpu: '100m'
      memory: '128Mi'
    limits:
      cpu: '500m'
      memory: '512Mi'
  secretName: backend-secrets
  env:
    redisUrl: 'redis://redis:6379'
    nodeEnv: 'production'
    nextApi: 'https://YOUR_CLUSTER_IP.nip.io'

frontend:
  name: popquiz-frontend
  image: abhaytopno/popquiz-frontend:v5
  port: 3000
  resources:
    requests:
      cpu: '100m'
      memory: '128Mi'
    limits:
      cpu: '500m'
      memory: '512Mi'
  env:
    nodeEnv: 'production'
    apiUrl: 'https://YOUR_CLUSTER_IP.nip.io'
    socketUrl: 'https://YOUR_CLUSTER_IP.nip.io'
    internalApiUrl: 'http://popquiz-backend-service'

ingress:
  host: popquiz.local
  tlsSecret: popquiz.local-tls
  className: nginx
