# services.yml
# --- Frontend Services ---
apiVersion: v1
kind: Service
metadata:
  name: popquiz-frontend-service-blue
  namespace: popquiz
spec:
  selector:
    app: popquiz-frontend
    version: blue
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: popquiz-frontend-service-green
  namespace: popquiz
spec:
  selector:
    app: popquiz-frontend
    version: green
  ports:
    - port: 80
      targetPort: 3000
# --- Backend Services ---
---
apiVersion: v1
kind: Service
metadata:
  name: popquiz-backend-service-blue
  namespace: popquiz
spec:
  selector:
    app: popquiz-backend
    version: blue
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: popquiz-backend-service-green
  namespace: popquiz
spec:
  selector:
    app: popquiz-backend
    version: green
  ports:
    - port: 80
      targetPort: 5000
