apiVersion: v1
kind: Service
metadata:
  name: popquiz-redis
  namespace: popquiz
spec:
  clusterIP: None
  selector:
    app: popquiz-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: popquiz-qdrant
  namespace: popquiz
spec:
  clusterIP: None
  selector:
    app: popquiz-qdrant
  ports:
    - name: http
      protocol: TCP
      port: 6333
      targetPort: 6333
    - name: grpc
      protocol: TCP
      port: 6334
      targetPort: 6334

---
apiVersion: v1
kind: Service
metadata:
  name: popquiz-langchain-blue
  namespace: popquiz
spec:
  selector:
    app: popquiz-langchain
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: popquiz-langchain-green
  namespace: popquiz
spec:
  selector:
    app: popquiz-langchain
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: popquiz-backend-blue
  namespace: popquiz
spec:
  selector:
    app: popquiz-backend
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: popquiz-backend-green
  namespace: popquiz
spec:
  selector:
    app: popquiz-backend
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: popquiz-frontend-blue
  namespace: popquiz
spec:
  selector:
    app: popquiz-frontend
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: popquiz-frontend-green
  namespace: popquiz
spec:
  selector:
    app: popquiz-frontend
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
