---
services:
  backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile.dev
    container_name: backend_dev
    ports:
      - '5000:5000'
    env_file:
      - ../backend/.env
    volumes:
      - ../backend:/usr/src/app:cached # Mount backend source code
      - /usr/src/app/node_modules # Prevent overwriting node_modules
      - /usr/src/app/dist # (optional) keep build artifacts inside container
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    command: pnpm run dev
    networks:
      - myapp-network
    depends_on:
      - redis

  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile.dev
    container_name: frontend_dev
    ports:
      - '3000:3000'
    env_file:
      - ../frontend/.env
    volumes:
      - ../frontend:/usr/src/app:cached # Mount frontend code for live reload
      - /usr/src/app/node_modules # Prevent overwriting node_modules
      - /usr/src/app/.next # (optional) preserve Next.js cache
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_DOCKER_BACKEND_API=http://backend:5000
    depends_on:
      - backend
    command: pnpm run dev # Use Next.js dev mode
    networks:
      - myapp-network

  redis:
    image: redis:7-alpine
    container_name: redis_dev
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - myapp-network

networks:
  myapp-network:
