---
services:
  backend:
    container_name: production_backend
    image: abhaytopno/popquiz-backend:v1.1
    restart: unless-stopped
    env_file:
      - ../backend/.env
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - '5000:5000'
    networks:
      - popquiz-network
    depends_on:
      - redis

  frontend:
    container_name: production_frontend
    image: abhaytopno/popquiz-frontend:v1.1
    restart: unless-stopped
    env_file:
      - ../frontend/.env
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - popquiz-network

  redis:
    image: redis:7-alpine
    container_name: production_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - popquiz-network

networks:
  popquiz-network:
