---
services:
  backend:
    container_name: production_backend
    image: abhaytopno/popquiz-backend:v10
    restart: unless-stopped
    env_file:
      - .env.backend
    ports:
      - '5000:5000'
    networks:
      - popquiz-network
    depends_on:
      - redis

  frontend:
    container_name: production_frontend
    image: abhaytopno/popquiz-frontend:v12
    restart: unless-stopped
    env_file:
      - .env.frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - popquiz-network

  redis:
    image: redis:7-alpine
    container_name: production_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - popquiz-network

networks:
  popquiz-network:
