---
services:
  backend:
    container_name: production_backend
    image: abhaytopno/popquiz-backend:v12
    restart: unless-stopped
    env_file:
      - .env.backend
    ports:
      - '5000:5000'
    networks:
      - popquiz-network
    depends_on:
      - redis
      - langchain

  frontend:
    container_name: production_frontend
    image: abhaytopno/popquiz-frontend:v12
    restart: unless-stopped
    env_file:
      - .env.frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - popquiz-network

  langchain:
    container_name: production_langchain
    image: abhaytopno/popquiz-langchain:v1
    restart: unless-stopped
    env_file:
      - .env.langchain
    ports:
      - '8000:8000'
    networks:
      - popquiz-network
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    container_name: production_qdrant
    restart: unless-stopped
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - popquiz-network

  redis:
    image: redis:7-alpine
    container_name: production_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - popquiz-network

networks:
  popquiz-network:

volumes:
  qdrant_data:
