services:
  production-backend:
    container_name: production-backend
    image: abhaytopno/popquiz-backend:v1.1
    env_file: ../backend/.env
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - '5000:5000'

  production-frontend:
    container_name: production-frontend
    image: abhaytopno/popquiz-frontend:v1.1
    env_file: ../frontend/.env
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - '3000:3000'

networks:
  app-network:
