apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ .Values.frontend.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: NODE_ENV
              value: {{ .Values.frontend.env.nodeEnv | quote }}
            - name: PORT
              value: {{ .Values.frontend.port | quote }}
            - name: API_URL
              value: {{ .Values.frontend.env.apiUrl | quote }}
            - name: SOCKET_URL
              value: {{ .Values.frontend.env.socketUrl | quote }}
            - name: INTERNAL_API_URL
              value: {{ .Values.frontend.env.internalApiUrl | quote }}
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}
